# Generated by Django 5.2.3 on 2025-06-24 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the author', max_length=255)),
                ('last_name', models.CharField(help_text='Last name of the author', max_length=255)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the author', unique=True)),
                ('slug', models.SlugField(editable=False, help_text='Slug for the author URL', max_length=255, unique=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of Birth', null=True)),
                ('date_of_death', models.DateField(blank=True, help_text='Date of Death', null=True)),
                ('awards', models.CharField(blank=True, help_text='Awards won by the author', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the author was created')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Timestamp when the author was last updated')),
            ],
        ),
    ]
