# Generated by Django 5.2.3 on 2025-06-22 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book', max_length=255)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the book', unique=True)),
                ('slug', models.SlugField(editable=False, help_text='Slug for the book URL', max_length=255, unique=True)),
                ('author', models.CharField(help_text='Author(s) of the book', max_length=255)),
                ('genre', models.CharField(help_text='Genre of the book', max_length=100)),
                ('published_date', models.DateField(blank=True, help_text='Date when the book was published', null=True)),
                ('isbn', models.CharField(help_text='ISBN number of the book', max_length=13, unique=True)),
                ('pages', models.IntegerField(blank=True, help_text='Number of pages in the book', null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image of the book', null=True, upload_to='book_covers/')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the book was created')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Timestamp when the book was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('device_info', models.CharField(max_length=255)),
                ('visit_time', models.DateTimeField()),
            ],
        ),
    ]
