# Generated by Django 5.2.3 on 2025-06-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVisit',
        ),
    ]
