# Generated by Django 5.2.3 on 2025-06-24 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0002_delete_uservisit'),
        ('drfapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Author(s) of the book', on_delete=django.db.models.deletion.CASCADE, related_name='Author', to='drfapp2.author'),
        ),
    ]
